#!  /bin/bash
#RM_SELINUX_RULE=enable
#
#  PRNL=brdcp7030lpr-2.0.2-1a.i386.deb
#  PRNC=cupswrapperDCP7030-2.0.2-1a.i386.deb
#  PRNP=
#  SCAN=brscan3-0.2.13-1.amd64.deb
#  SKEY=brscan-skey-0.3.2-0.amd64.deb
#
if ! [ -f /etc/init.d/cupsys ];then
 DUMMYCUPSYS=1
 ln -s /bin/true  /etc/init.d/cupsys
fi
if ! [ -f /etc/init.d/cups ];then
 DUMMYCUPS=1
 ln -s /bin/true  /etc/init.d/cups
fi
if ! [ -f /etc/init.d/lpd ];then
 DUMMYLPD=1
 ln -s /bin/true  /etc/init.d/lpd
fi
if ! [ -f /etc/init.d/lprng ];then
 DUMMYLPRNG=1
 ln -s /bin/true  /etc/init.d/lprng
fi
dpkg  -x cupswrapperDCP7030-2.0.2-1.i386.deb /
dpkg  -P    cupswrapperDCP7030:i386
dpkg  -x brdcp7030lpr-2.0.2-1.i386.deb /
dpkg  -P    brdcp7030lpr:i386
if [ "$DUMMYCUPS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cups  2> /dev/null| grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/cups
  fi
fi

if [ "$DUMMYCUPSYS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cupsys  2> /dev/null| grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/cupsys
  fi
fi

if [ "$DUMMYLPD" = 1 ];then
  lsc=$(ls -al /etc/init.d/lpd  2> /dev/null | grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/lpd
  fi
fi

if [ "$DUMMYLPRNG" = 1 ];then
  lsc=$(ls -al /etc/init.d/lprng | grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/lprng
  fi
fi


